export const ACTIONS_COUNT = 3;

export const EVENT_LIST = "EVENT_LIST";
export const GROUP_LIST_REQUEST = "GROUP_LIST_REQUEST";
export const EVENT_LIST_SUCCESS = "EVENT_LIST_SUCCESS";
export const EVENT_LIST_FAILURE = "EVENT_LIST_FAILURE";

export const EVENT_CREATE = "EVENT_CREATE";
export const EVENT_CREATE_REQUEST = "EVENT_CREATE_REQUEST";
export const EVENT_CREATE_SUCCESS = "EVENT_CREATE_SUCCESS";
export const EVENT_CREATE_FAILURE = "EVENT_CREATE_FAILURE";

export const PARTICIPANT_LIST = "PARTICIPANT_LIST";
export const PARTICIPANT_LIST_REQUEST = "PARTICIPANT_LIST_REQUEST";
export const PARTICIPANT_LIST_SUCCESS = "PARTICIPANT_LIST_SUCCESS";
export const PARTICIPANT_LIST_FAILURE = "PARTICIPANT_LIST_FAILURE";

export const PARTICIPANT_CREATE = "PARTICIPANT_CREATE";
export const PARTICIPANT_CREATE_REQUEST = "PARTICIPANT_CREATE_REQUEST";
export const PARTICIPANT_CREATE_SUCCESS = "PARTICIPANT_CREATE_SUCCESS";
export const PARTICIPANT_CREATE_FAILURE = "PARTICIPANT_CREATE_FAILURE";

export const SIGN_UP = "SIGN_UP";
export const SIGN_UP_REQUEST = "SIGN_UP_REQUEST";
export const SIGN_UP_SUCCESS = "SIGN_UP_SUCCESS";
export const SIGN_UP_FAILURE = "SIGN_UP_FAILURE";
